import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: "t7cZfWIq-a",
    firstName: "Aman",
    lastName: "Harsh",
    username: "amanharsh",
    password: "amanharsh123",
    bio: "Frontend Developer",
    bookmarks: [],
    avatarUrl: "https://example.com/avatars/alice-smith.jpg",
    website: "https://example.com/",
    createdAt: "2023-01-01T10:55:06+05:30",
    updatedAt: formatDate(),
  },
  {
    _id: "t7cZfWIp-q",
    firstName: "Alice",
    lastName: "Smith",
    username: "alicesmith",
    password: "aliceSmith123",
    bio: "Be yourself!",
    bookmarks: [],
    avatarUrl: "https://example.com/avatars/alice-smith.jpg",
    website: "https://example.com/",
    createdAt: "2023-01-01T10:55:06+05:30",
    updatedAt: formatDate(),
  },
  {
    _id: "79Gksh9otl",
    firstName: "Bob",
    lastName: "Johnson",
    username: "bobjohnson",
    password: "bobJohnson123",
    bio: "Hello World",
    bookmarks: [],
    avatarUrl: "https://example.com/avatars/bob-johnson.jpg",
    website: "https://example.com/",
    createdAt: "2023-01-02T10:55:06+05:30",
    updatedAt: formatDate(),
  },
  {
    _id: "1T6Be1QpLm",
    firstName: "Carol",
    lastName: "Williams",
    username: "carolwilliams",
    password: "carolWilliams123",
    bio: "What's in bio?",
    bookmarks: [],
    avatarUrl: "https://example.com/avatars/carol-williams.jpg",
    website: "https://example.com/",
    createdAt: "2023-01-01T10:55:06+05:30",
    updatedAt: formatDate(),
  },
  {
    _id: "LCrc9f0Zl0",
    firstName: "David",
    lastName: "Brown",
    username: "davidbrown",
    password: "davidBrown123",
    bio: "What's in bio?",
    avatarUrl: "https://example.com/avatars/david-brown.jpg",
    website: "https://example.com/",
    createdAt: "2023-01-03T10:55:06+05:30",
    updatedAt: formatDate(),
  },
  {
    _id: "o5gzWjEeX_",
    firstName: "Emma",
    lastName: "Davis",
    username: "emmadavis",
    password: "emmaDavis123",
    bio: "Aspiring Frontend Engineer",
    bookmarks: [],
    avatarUrl: "https://example.com/avatars/emma-davis.jpg",
    website: "https://example.com/",
    createdAt: "2023-01-04T10:55:06+05:30",
    updatedAt: formatDate(),
  },
  {
    _id: "M1NR81Bzlz",
    firstName: "Frank",
    lastName: "Wilson",
    username: "frankwilson",
    password: "frankWilson123",
    bio: "What's up?",
    bookmarks: [],
    avatarUrl: "https://example.com/avatars/frank-wilson.jpg",
    website: "",
    createdAt: "2023-01-05T10:55:06+05:30",
    updatedAt: formatDate(),
  },
  {
    _id: "qq8zWjEeXd",
    firstName: "Grace",
    lastName: "Martinez",
    username: "gracemartinez",
    password: "graceMartinez123",
    bio: "Frontend Engineer",
    bookmarks: [],
    avatarUrl: "https://example.com/avatars/grace-martinez.jpg",
    website: "",
    createdAt: "2023-01-06T10:55:06+05:30",
    updatedAt: formatDate(),
  },
];
